# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Spring 2017'
tagline:          'A GAP workshop'
description:      'Workshop: May 29 - June 2'
location:         'RWTH Aachen University'
url:              http://gapdays.de
baseurl:          /gapdays2017-spring


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.*", "misc" ]
include: [ "program.pdf" ]
